bbcjournal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from profiles.views import register_view, login_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^profiles/', include('profiles.urls', namespace='profiles')),

    url(r'^courses/', include('courses.urls', namespace='courses')),

    url(r'^$', RedirectView.as_view(url='courses/'))
]

courses/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^add_lesson', LessonCreateView.as_view(), name = 'add_lesson'),
    url(r'^lesson/(?P<pk>\d+)', LessonDetailView.as_view(), name = 'lesson_detail'),
    url(r'^edit_lesson/(?P<pk>\d+)', lesson_edit_view, name = 'lesson_edit'),
    url(r'^teacher_lesson/(?P<pk>\d+)', teacher_lessons_view, name = 'teacher_lessons'),
    url(r'^student_lesson/(?P<pk>\d+)', student_lessons_view, name = 'student_lessons'),
    url(r'^group_journal/(?P<pk>\d+)', group_journal_view, name = 'groups_journal'),

    url(r'^create', CourseCreateView.as_view(), name='course_create'),
    url(r'(?P<pk>\d+)', CourseDetailView.as_view(), name='course_detail'),
    url(r'^$', CoursesView.as_view(), name='courses')
]

profiles/urls.py
from django.conf.urls import url

from .views import *

urlpatterns =[
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^password/', change_password_view, name='change_password'),

    url(r'^students/(?P<pk>\d+)', UpdateStudentView.as_view(), name='students_detail'),
    url(r'^teachers/(?P<pk>\d+)', UpdateTeacherView.as_view(), name='teachers_detail'),

    url(r'^groups/add', GroupCreateView.as_view(), name='groups_add'),
    url(r'^groups/delete/(?P<pk>\d+)', GroupDeleteView.as_view(), name='groups_delete'),
    url(r'^groups/(?P<pk>\d+)', GroupDetailView.as_view(), name='groups_detail'),

    url(r'^students', StudentsView.as_view(), name='students'),
    url(r'^teachers', TeachersView.as_view(), name='teachers'),
    url(r'^groups', GroupsView.as_view(), name='groups'),
]

templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

templates/snippets/js.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

templates/snippets/nav.html
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	  </button>
	  <a class="navbar-brand" href="{% url 'profiles:groups' %}">Журнал языкового клуба BBC</a>
	</div>
	<div id="navbar" class="navbar-collapse collapse">
	  <ul class="nav navbar-nav">
		  {% if user.is_authenticated %}
		<li><a href="{% url 'courses:courses' %}">Курсы</a></li>
		<li><a href="{% url 'profiles:change_password' %}">Сменить пароль</a></li>
	  </ul>
	  <ul class="nav navbar-nav navbar-right">
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Администрирование<span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><a href="{% url 'profiles:teachers' %}">Учителя</a></li>
				<li><a href="{% url 'profiles:students' %}">Студенты</a></li>
				<li><a href="{% url 'profiles:groups' %}">Группы</a></li>
			</ul>
		</li>

			<li><a href="{% url 'profiles:logout' %}">Выход</a></li>
		  {% endif %}
	  </ul>
	</div>
  </div>
</nav>