bbcjournal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from profiles.views import register_view, login_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^profiles/', include('profiles.urls', namespace='profiles')),

    url(r'^courses/', include('courses.urls', namespace='courses')),

    url(r'^$', RedirectView.as_view(url='courses/'))
]

courses/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^add_lesson', LessonCreateView.as_view(), name = 'add_lesson'),
    url(r'^lesson/(?P<pk>\d+)', LessonDetailView.as_view(), name = 'lesson_detail'),
    url(r'^edit_lesson/(?P<pk>\d+)', lesson_edit_view, name = 'lesson_edit'),
    url(r'^teacher_lesson/(?P<pk>\d+)', teacher_lessons_view, name = 'teacher_lessons'),
    url(r'^student_lesson/(?P<pk>\d+)', student_lessons_view, name = 'student_lessons'),
    url(r'^group_journal/(?P<pk>\d+)', group_journal_view, name = 'groups_journal'),

    url(r'^create', CourseCreateView.as_view(), name='course_create'),
    url(r'(?P<pk>\d+)', CourseDetailView.as_view(), name='course_detail'),
    url(r'^$', CoursesView.as_view(), name='courses')
]

profiles/urls.py
from django.conf.urls import url

from .views import *

urlpatterns =[
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^password/', change_password_view, name='change_password'),

    url(r'^students/(?P<pk>\d+)', UpdateStudentView.as_view(), name='students_detail'),
    url(r'^teachers/(?P<pk>\d+)', UpdateTeacherView.as_view(), name='teachers_detail'),

    url(r'^groups/add', GroupCreateView.as_view(), name='groups_add'),
    url(r'^groups/delete/(?P<pk>\d+)', GroupDeleteView.as_view(), name='groups_delete'),
    url(r'^groups/(?P<pk>\d+)', GroupDetailView.as_view(), name='groups_detail'),

    url(r'^students', StudentsView.as_view(), name='students'),
    url(r'^teachers', TeachersView.as_view(), name='teachers'),
    url(r'^groups', GroupsView.as_view(), name='groups'),
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save

class ProfileGroup(models.Model):
    name = models.CharField(max_length=255, verbose_name = 'Имя группы')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Profile(models.Model):
    type_choises = (
        ('A', 'Администратор'),
        ('T', 'Учитель'),
        ('S', 'Студент')
    )

    user = models.OneToOneField(User)
    user_type = models.CharField(max_length=1, choices=type_choises, default="T")
    full_name = models.CharField(max_length=255, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    group = models.ForeignKey(ProfileGroup, blank=True, null=True, on_delete=models.SET_NULL)
    deactivation_date = models.DateField(blank=True, null=True)

    is_password_changed = models.BooleanField(default = False)

    def __str__(self):
        return self.user.username

    def __unicode__(self):
        return self.user.username

def post_save_user_receiver(sender, instance, created, **kwargs):
    if created:
       profile, is_created = Profile.objects.get_or_create(user=instance)

post_save.connect(post_save_user_receiver, sender=User)

profiles/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

import cyrtranslit
from django.template.defaultfilters import date
from django.utils import formats
from random import randrange

from .models import Profile

User = get_user_model()

type_choises = type_choises = (
        ('T', 'Учитель'),
        ('S', 'Студент')
    )

class DateInput(forms.DateInput):
    input_type = 'date'

    def _format_value(self, value):
        return value

class CreateUserForm(forms.ModelForm):
    full_name = forms.CharField(label="ФИО")
    birth_date = forms.DateField(label="Дата рождения", widget=DateInput)
    user_type = forms.ChoiceField(label="Тип пользователя", choices=type_choises)

    class Meta:
        model = User
        fields = []

    def clean_full_name(self):
        full_name = self.cleaned_data['full_name']
        fio = full_name.split()
        if len(fio) < 2:
            raise ValidationError('Неверный формат ФИО')
        return full_name

    def save(self, commit = True):
        user = super(CreateUserForm, self).save(commit = False)
        user.set_password("password")
        user.is_active = True

        full_name = self.cleaned_data.get('full_name')
        full_name_en = cyrtranslit.to_latin(full_name, 'ru')
        full_name_clean = full_name_en.replace('#', '')
        full_name_clean = full_name_clean.replace("'", "")

        fio = full_name_clean.split()
        if len(fio) == 2:
            username = fio[1][0].lower() + fio[0].lower()
        else:
            username = fio[1][0].lower() + fio[2][0].lower() + fio[0].lower()
        same_name_users = User.objects.filter(username__iexact=username)
        if same_name_users:
            username += str(randrange(100))
        user.username = username

        if commit:
            user.save()
            user.profile.birth_date = self.cleaned_data.get("birth_date")
            user.profile.full_name = self.cleaned_data.get("full_name")
            user.profile.user_type = self.cleaned_data.get("user_type")
            user.profile.save()
        return user

class UserLoginForm(forms.Form):
    username = forms.CharField(label='Имя пользователя', validators=[RegexValidator(
                        regex = '^[a-zA-Z0-9.@+-]*$',
                        message = 'Имя пользователя может содержать латинские буквы, цифры и следующие символы: ". @ + -" ',
                        code='invalid_username'
                    )])
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        # the_user = authenticate(username=username, password=password)
        # if not the_user:
        #     raise forms.ValidationError("Invalid credentials")
        user_obj = User.objects.filter(username=username).first()
        if not user_obj:
            raise forms.ValidationError("Invalid credentials")
        else:
            if not user_obj.check_password(password):
                # log auth tries
                raise forms.ValidationError("Invalid credentials")
        return super(UserLoginForm, self).clean(*args, **kwargs)

class UpdateStudentForm(forms.ModelForm):
    user_type = forms.ChoiceField(label="Тип пользователя", choices=type_choises)

    class Meta:
        model = Profile
        fields = ['full_name',
                  'birth_date',
                  'user_type',
                  'group']
        widgets = {'birth_date': DateInput}
        labels = {
            'full_name': 'ФИО',
            'birth_date': 'Дата рождения',
            'user_type': 'Тип пользователя',
            'group': 'Группа'
        }


class UpdateTeacherForm(forms.ModelForm):
    user_type = forms.ChoiceField(label="Тип пользователя", choices=type_choises)

    class Meta:
        model = Profile
        fields = ['full_name',
                  'birth_date',
                  'user_type']
        widgets = {'birth_date': DateInput}
        labels = {
            'full_name': 'ФИО',
            'birth_date': 'Дата рождения',
            'user_type': 'Тип пользователя'
        }

profiles/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from django.contrib.auth import login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.views.generic.detail import DetailView

from .models import *

User = get_user_model()

from .forms import CreateUserForm, UserLoginForm, UpdateStudentForm, UpdateTeacherForm

@login_required(login_url='/profiles/login')
def register_view(request, *args, **kwargs):
    permissions = False
    if request.user.profile.user_type == 'A':
        permissions = True
    template_name = 'registration/register.html'
    form = CreateUserForm(request.POST or None)
    if form.is_valid():
        form.save()
        if form.cleaned_data['user_type'] == 'T':
            return HttpResponseRedirect('/profiles/teachers')
        elif form.cleaned_data['user_type'] == 'S':
            return HttpResponseRedirect('/profiles/students')
        else:
            return HttpResponseRedirect('/')
    return render(request, template_name, {'form': form, 'permissions': permissions})

def login_view(request, *args, **kwargs):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/courses')
    template_name = 'registration/login.html'
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username_ = form.cleaned_data.get('username')
        user_obj = User.objects.get(username__iexact=username_)
        print(user_obj)
        login(request, user_obj)
        if not user_obj.profile.is_password_changed:
            return redirect('profiles:change_password')
        return HttpResponseRedirect('/courses')
    return render(request, template_name, {'form': form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/profiles/login')

class StudentsView(LoginRequiredMixin,ListView):
    model = Profile

    login_url = '/profiles/login'

    def get_queryset(self):
        return Profile.objects.filter(Q(user_type__iexact='S') & Q(user__is_active=True))

    def get_context_data(self, **kwargs):
        context = super(StudentsView, self).get_context_data(**kwargs)
        context['type'] = 'S'
        return context

class TeachersView(LoginRequiredMixin, ListView):
    model = Profile

    login_url = '/profiles/login'

    def get_queryset(self):
        return Profile.objects.filter(Q(user_type__iexact='T') & Q(user__is_active=True))

    def get_context_data(self, **kwargs):
        context = super(TeachersView, self).get_context_data(**kwargs)
        context['type'] = 'T'
        return context

class GroupsView(LoginRequiredMixin, ListView):
    model = ProfileGroup

    login_url = '/profiles/login'

class UpdateStudentView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = UpdateStudentForm
    success_url = '/profiles/students'

    login_url = '/profiles/login'

    user_full_name = ''
    username = ''
    user_type = ''
    user_id = ''

    def get_object(self, queryset=None):
        profile = Profile.objects.filter(pk=self.kwargs['pk'])[0]
        self.user_full_name = profile.full_name
        self.username = profile.user.username
        self.user_type = profile.user_type
        self.user_id = profile.pk
        return profile

    def get_context_data(self, **kwargs):
        context = super(UpdateStudentView, self).get_context_data(**kwargs)
        permissions = False
        if self.request.user.profile.user_type == 'A':
            permissions = True
        context['permissions'] = permissions
        context['user_full_name'] = self.user_full_name
        context['username'] = self.username
        context['user_type'] = self.user_type
        context['user_id'] = self.user_id
        return context

class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = UpdateTeacherForm
    success_url = '/profiles/teachers'

    login_url = '/profiles/login'

    user_full_name = ''
    username = ''
    user_type = ''
    user_id = ''

    def get_object(self, queryset=None):
        profile = Profile.objects.filter(pk=self.kwargs['pk'])[0]
        self.user_full_name = profile.full_name
        self.username = profile.user.username
        self.user_type = profile.user_type
        self.user_id = profile.pk
        return profile

    def get_context_data(self, **kwargs):
        context = super(UpdateTeacherView, self).get_context_data(**kwargs)
        permissions = False
        if self.request.user.profile.user_type == 'A':
            permissions = True
        context['permissions'] = permissions
        context['user_full_name'] = self.user_full_name
        context['username'] = self.username
        context['user_type'] = self.user_type
        context['user_id'] = self.user_id
        return context

class GroupDetailView(LoginRequiredMixin, DetailView):
    model = ProfileGroup

    login_url = '/profiles/login'

    def get_context_data(self, **kwargs):
        context = super(GroupDetailView, self).get_context_data(**kwargs)
        object = kwargs.get('object')
        students = Profile.objects.filter(group=object.pk)
        permissions = False
        if self.request.user.profile.user_type == 'A':
            permissions = True
        context['permissions'] = permissions
        context['students'] = students
        context['group_name'] = object.name
        context['group_id'] = object.pk
        return context

class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = ProfileGroup
    success_url = '/profiles/groups'

    login_url = '/profiles/login'

class GroupCreateView(LoginRequiredMixin, CreateView):
    model = ProfileGroup
    success_url = '/profiles/groups'
    fields = ['name']

    login_url = '/profiles/login'

    def get_context_data(self, **kwargs):
        context = super(GroupCreateView, self).get_context_data(**kwargs)
        permissions = False
        if self.request.user.profile.user_type == 'A':
            permissions = True
        context['permissions'] = permissions
        return context

@login_required(login_url='/profiles/login')
def change_password_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            user.profile.is_password_changed = True
            user.profile.save()
            user.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('courses:courses')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'profiles/change_password.html', {
        'form': form,
        'user_name': request.user.username,
        'is_password_changed': request.user.profile.is_password_changed
    })

templates/profiles/change_password.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}

<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>Смена пароля</h2>
    <h4>Пользователь {{ user_name }}</h4>
    {% if not is_password_changed %}
    <p style="color: red">Необходимо сменить пароль</p>
    {% endif %}
    <form method="post">
  {% csrf_token %}
  {{ form|bootstrap }}
  <button type="submit" class="btn btn-lg btn-primary">Сохранить</button>
</form>
</div>

{% endblock %}

templates/profiles/profile_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>{{ user_full_name }}</h2>
    <hr/>
    <h4><b>Имя пользователя:</b> {{ username }}</h4>
    <hr/>
    {% if permissions %}
    <form class='text-left' method="post" action="">
    {% csrf_token %}

        {{ form|bootstrap }}

    <input class="btn btn-lg btn-primary" type="submit" value="Сохранить" />
    </form>
    {% else %}
        <h2 style="color: red">У Вас нет прав на редактирование профилей пользователей</h2>
    {% endif %}
    <br>
    {% if user_type == 'T' %}
    <a href="{% url 'courses:teacher_lessons' user_id %}" class="btn btn-lg btn-primary">Просмотреть последние уроки</a>
    {% elif user_type == 'S' %}
    <a href="{% url 'courses:student_lessons' user_id %}" class="btn btn-lg btn-primary">Просмотреть последние уроки</a>
    {% endif %}

</div>

{% endblock %}

templates/profiles/profile_list.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    {% if type == 'S' %}
    <h2>Студенты</h2>
    <hr/>
    <div class="list-group">
        {% for profile in object_list %}
		<a href="{% url 'profiles:students_detail' profile.pk %}" class="list-group-item list-group-item-action">{{ profile.full_name }}</a>
        {% endfor %}
	</div>
    {% else %}
    <h2>Учителя</h2>
    <hr/>
    <div class="list-group">
    {% for profile in object_list %}
		<a href="{% url 'profiles:teachers_detail' profile.pk %}" class="list-group-item list-group-item-action">{{ profile.full_name }}</a>
    {% endfor %}
    </div>
    {% endif %}
    <a href="{% url 'profiles:register' %}" class="btn btn-lg btn-primary">Добавить нового пользователя</a>


</div>

{% endblock %}

templates/profiles/profilegroup_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>Удаление группы</h2>
    <hr/>
    <div class="list-group">
        <form class='text-left' action="" method="post">{% csrf_token %}
            <p>Вы действительно хотите удалить "{{ object }}"?</p>
            <input class="btn btn-lg btn-primary" type="submit" value="Да" />
        </form>
	</div>
</div>

{% endblock %}

templates/profiles/profilegroup_detail.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>{{ group_name }}</h2>
    <hr/>
    <div class="list-group">
        <h3>Студенты</h3>
        {% for student in students %}
		<a href="{% url 'profiles:students_detail' student.pk %}" class="list-group-item list-group-item-action">{{ student.full_name }}</a>
        {% endfor %}
	</div>
    {% if permissions %}
    <a href="{% url 'profiles:groups_delete' group_id %}" class="btn btn-lg btn-primary">Удалить группу</a>
    {% endif%}
    <br>
    <br>
    <a href="{% url 'courses:groups_journal' group_id %}" class="btn btn-lg btn-primary">Журнал группы</a>
</div>

{% endblock %}

templates/profiles/profilegroup_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    {% if permissions %}
    <h2>Новая группа</h2>
    <hr/>
    <form class='text-left' method="post" action="{% url 'profiles:groups_add' %}">
    {% csrf_token %}

        {{ form|bootstrap }}

    <input class="btn btn-lg btn-primary" type="submit" value="Сохранить" />
    </form>
    {% else %}
        <h2 style="color: red">У Вас нет прав на добавление новых пользователей</h2>
    {% endif %}

</div>

{% endblock %}

templates/profiles/profilegroup_list.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>Группы</h2>
    <hr/>
    <div class="list-group">
        {% for profilegroup in object_list %}
		<a href="{% url 'profiles:groups_detail' profilegroup.pk %}" class="list-group-item list-group-item-action">{{ profilegroup.name }}</a>
        {% endfor %}
	</div>
    <a href="{% url 'profiles:groups_add' %}" class="btn btn-lg btn-primary">Добавить новую группу</a>
</div>

{% endblock %}