bbcjournal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from profiles.views import register_view, login_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^profiles/', include('profiles.urls', namespace='profiles')),

    url(r'^courses/', include('courses.urls', namespace='courses')),

    url(r'^$', RedirectView.as_view(url='courses/'))
]

courses/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^add_lesson', LessonCreateView.as_view(), name = 'add_lesson'),
    url(r'^lesson/(?P<pk>\d+)', LessonDetailView.as_view(), name = 'lesson_detail'),
    url(r'^edit_lesson/(?P<pk>\d+)', lesson_edit_view, name = 'lesson_edit'),
    url(r'^teacher_lesson/(?P<pk>\d+)', teacher_lessons_view, name = 'teacher_lessons'),
    url(r'^student_lesson/(?P<pk>\d+)', student_lessons_view, name = 'student_lessons'),
    url(r'^group_journal/(?P<pk>\d+)', group_journal_view, name = 'groups_journal'),

    url(r'^create', CourseCreateView.as_view(), name='course_create'),
    url(r'(?P<pk>\d+)', CourseDetailView.as_view(), name='course_detail'),
    url(r'^$', CoursesView.as_view(), name='courses')
]

profiles/urls.py
from django.conf.urls import url

from .views import *

urlpatterns =[
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^password/', change_password_view, name='change_password'),

    url(r'^students/(?P<pk>\d+)', UpdateStudentView.as_view(), name='students_detail'),
    url(r'^teachers/(?P<pk>\d+)', UpdateTeacherView.as_view(), name='teachers_detail'),

    url(r'^groups/add', GroupCreateView.as_view(), name='groups_add'),
    url(r'^groups/delete/(?P<pk>\d+)', GroupDeleteView.as_view(), name='groups_delete'),
    url(r'^groups/(?P<pk>\d+)', GroupDetailView.as_view(), name='groups_detail'),

    url(r'^students', StudentsView.as_view(), name='students'),
    url(r'^teachers', TeachersView.as_view(), name='teachers'),
    url(r'^groups', GroupsView.as_view(), name='groups'),
]

courses/models.py
from django.db import models
from profiles.models import Profile, ProfileGroup
from django.core.validators import MaxValueValidator

import datetime

import string

# Create your models here.

class Course(models.Model):
    name = models.CharField(max_length = 255, verbose_name = 'Название курса')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Lesson(models.Model):
    type_choises = (('U', 'Обычный урок'),
                    ('T', 'Тестирование'),
                    ('E', 'Пробный'))
    name = models.CharField(max_length = 255, verbose_name = 'Название урока')
    description = models.TextField(blank = True, default='', verbose_name = 'Описание урока')
    homework = models.TextField(blank = True, default='', verbose_name = 'Домашнее задание')
    date = models.DateField(blank = False, null = False, verbose_name = 'Дата урока', default = datetime.date.today)
    type = models.CharField(max_length = 1, choices = type_choises, default = 'U', verbose_name = 'Тип')

    course = models.ForeignKey(Course, null = True, verbose_name = 'Курс')
    teacher = models.ForeignKey(Profile, null = True, verbose_name = 'Учитель')
    group = models.ForeignKey(ProfileGroup, null = True, verbose_name = 'Группа')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class StudentLesson(models.Model):
    mark_types = (('A', 'A'),
                  ('B', 'B'),
                  ('C', 'C'),
                  ('D', 'D'),
                  ('E', 'E'),
                  ('F', 'F'),
                  ('-', '-'))
    student = models.ForeignKey(Profile, blank = False, null = False)
    lesson = models.ForeignKey(Lesson, blank = False, null = False)

    mark = models.CharField(max_length = 1, choices = mark_types, default = '')
    mark_testing = models.PositiveIntegerField(validators = [MaxValueValidator(100)], blank = True, null = True)
    precense = models.BooleanField(default = True)
    reason_for_abcense = models.CharField(max_length = 255, blank = True, default = '')

    def __str__(self):
        return self.student.full_name + ' ' + self.lesson.name

    def __unicode__(self):
        return self.student.full_name + ' ' + self.lesson.name

courses/forms.py
from django import forms

from .models import Lesson, StudentLesson

class DateInput(forms.DateInput):
    input_type = 'date'

class LessonCreateForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['name', 'course', 'group', 'type', 'description', 'date']
        widgets = {'date': DateInput}

class StudentLessonEditForm(forms.Form):
    is_presence = forms.BooleanField(initial = True)
    mark = forms.ChoiceField(choices = StudentLesson.mark_types)
    reason_for_abcense = forms.CharField(widget = forms.TextInput)

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .models import Course, Lesson, StudentLesson
from .forms import LessonCreateForm, StudentLessonEditForm

from profiles.models import Profile, ProfileGroup

# Create your views here.

class CoursesView(LoginRequiredMixin, ListView):
    model = Course

    login_url = '/profiles/login'

class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    fields = '__all__'
    success_url = '/courses'

    login_url = '/profiles/login'

    def get_context_data(self, **kwargs):
        context = super(CourseCreateView, self).get_context_data(**kwargs)
        permissions = False
        if self.request.user.profile.user_type == 'A':
            permissions = True
        context['permissions'] = permissions
        return context

class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course

    login_url = '/profiles/login'

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        object = kwargs.get('object')
        lessons = Lesson.objects.filter(course=object.pk)
        context['lessons'] = lessons
        return context

class LessonCreateView(LoginRequiredMixin, CreateView):
    model = Lesson
    form_class = LessonCreateForm

    login_url = '/profiles/login'

    def get_success_url(self):
        return '/courses/edit_lesson/' + str(self.object.pk)

    def get_context_data(self, **kwargs):
        context = super(LessonCreateView, self).get_context_data(**kwargs)
        permissions = False
        if self.request.user.profile.user_type == 'T':
            permissions = True
        context['permissions'] = permissions
        return context

    def form_valid(self, form):
        form.instance.teacher = Profile.objects.filter(user=self.request.user)[0]
        form.save()

        lesson = super(LessonCreateForm, form).save(commit=False)

        group = form.cleaned_data.get('group')
        students = Profile.objects.filter(group=group)

        for student in students:
            student_lesson = StudentLesson(student = student, lesson = lesson)
            student_lesson.save()

        return super(LessonCreateView, self).form_valid(form)

class LessonDetailView(LoginRequiredMixin, DetailView):
    model = Lesson

    login_url = '/profiles/login'

    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        lesson = kwargs['object']
        student_lessons = StudentLesson.objects.filter(lesson=lesson)
        context['student_lessons'] = student_lessons
        return context

class LessonEditView(LoginRequiredMixin, UpdateView):
    model = Lesson
    fields = ['homework']
    template_name = 'courses/student_lesson_edit.html'

    login_url = '/profiles/login'

def get_students_pk(post):
    pks = {}
    for key in post:
        f = key.find('-')
        if f >= 0:
            n = key[f + 1:]
            if n not in pks:
                pks[n] = {}
            pks[n][key[:f]] = post[key]
    return pks

@login_required(login_url='/profiles/login')
def lesson_edit_view(request, *args, **kwargs):
    permissions = False
    if request.user.profile.user_type == 'T':
        permissions = True
    template_name = 'courses/student_lesson_edit.html'
    if request.POST:
        pks = get_students_pk(request.POST)
        for pk in pks:
            student_lesson = StudentLesson.objects.filter(Q(student = pk) & Q(lesson = kwargs.get('pk')))[0]
            student_lesson.lesson.homework = request.POST['homework']
            student_lesson.lesson.save()
            if 'precense' in pks[pk]:
                student_lesson.precense = True
            else:
                student_lesson.precense = False
            if student_lesson.precense:
                student_lesson.mark = pks[pk]['mark']
            else:
                student_lesson.reason_for_abcense = pks[pk]['reason_for_abcense']
            student_lesson.save()
        return HttpResponseRedirect('/')
    else:
        student_lessons = StudentLesson.objects.filter(lesson = kwargs.get('pk'))
        return render(request, template_name, {'student_lessons': student_lessons, 'permissions': permissions})

@login_required(login_url='/profiles/login')
def teacher_lessons_view(request, *args, **kwargs):
    template_name = 'courses/teacher_lessons.html'
    profile = Profile.objects.filter(pk=kwargs['pk'])[0]
    user_full_name = profile.full_name
    lessons_query = Lesson.objects.filter(teacher=kwargs['pk']).order_by('-id')[:10]
    lessons = []
    n = 0
    for lesson in lessons_query:
        lessons.append({})
        lessons[n]['name'] = lesson.name
        lessons[n]['date'] = lesson.date
        lessons[n]['type'] = lesson.get_type_display()
        lessons[n]['course'] = lesson.course.name
        students = StudentLesson.objects.filter(lesson=lesson)
        lessons[n]['students'] = len(students)
        n += 1

    return render(request, template_name, {'lessons': lessons, 'user_full_name': user_full_name})

@login_required(login_url='/profiles/login')
def student_lessons_view(request, *args, **kwargs):
    template_name = 'courses/student_lessons.html'
    profile = Profile.objects.filter(pk=kwargs['pk'])[0]
    user_full_name = profile.full_name
    lessons = StudentLesson.objects.filter(student=kwargs['pk']).order_by('-id')[:10]
    return render(request, template_name, {'lessons': lessons, 'user_full_name': user_full_name})

@login_required(login_url='/profiles/login')
def group_journal_view(request, *args, **kwargs):
    template_name = 'courses/group_journal.html'
    group = ProfileGroup.objects.filter(pk=kwargs['pk'])[0]
    students = Profile.objects.filter(group=group)
    student_lessons = []
    for student in students:
        student_lessons_query = StudentLesson.objects.filter(student=student)[:10]
        student_lessons.append(student_lessons_query)
    return render(request, template_name, {'student_lessons': student_lessons})

templates/courses/course_detail.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>{{ object.name }}</h2>
    <hr/>
    <div class="list-group">
        <h3>Уроки</h3>
        {% for lesson in lessons %}
		<a href="{% url 'courses:lesson_detail' lesson.pk %}" class="list-group-item list-group-item-action">{{ lesson.name }}</a>
        {% endfor %}
	</div>
	<a href="{% url 'courses:add_lesson' %}" class="btn btn-lg btn-primary">Добавить новый урок</a>

</div>

{% endblock %}

templates/courses/course_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    {% if permissions %}
    <h2>Новый курс</h2>
    <hr/>
    <form class='text-left' method="post" action="">
    {% csrf_token %}

        {{ form|bootstrap }}

    <input class="btn btn-lg btn-primary" type="submit" value="Сохранить" />
    </form>
    {% else %}
        <h2 style="color: red">У Вас нет прав на добавление новых курсов</h2>
    {% endif %}
	
	{% if user_type == 'T' %}
	{% endif %}

</div>

{% endblock %}

templates/courses/course_list.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>Курсы</h2>
    <hr/>
    <div class="list-group">
        {% for course in object_list %}
		<a href="{{ course.pk }}" class="list-group-item list-group-item-action">{{ course.name }}</a>
        {% endfor %}
	</div>
	<a href="{% url 'courses:course_create' %}" class="btn btn-lg btn-primary">Добавить новый курс</a>

</div>

{% endblock %}

templates/courses/group_journal.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}

<style>
    th, td {
	text-align: center;
	vertical-align: middle;
}

</style>

<div class='col-sm-offset-0 text-left'>
    <div class="panel panel-info">
        <div class="panel-heading">Результаты группы</div>
        <div class="panel-body">
            <table class="table table-bordered">
                <tr>
                    {% if student_lessons.0 %}
                    <th>ФИО ученика</th>
                    {% endif %}
                    {% for student_lesson in student_lessons.0 %}
                    <td><a href="{% url 'courses:lesson_detail' student_lesson.lesson.pk %}">{{ student_lesson.lesson.date|date:"d M" }}</a></td>
                    {% endfor %}
                </tr>
                {% for student_lesson_set in student_lessons %}
                <tr>
                    {% if student_lesson_set.0 %}
                    <th><a href="{% url 'profiles:students_detail' student_lesson_set.0.student.pk %}">{{ student_lesson_set.0.student.full_name }}</a></th>
                    {% endif %}
                    {% for student_lesson in student_lesson_set %}

                    {% if student_lesson.precense %}
                    <td class="bg-success">{{ student_lesson.mark }}</td>
                    {% else %}
                    <td class="bg-danger">{{ student_lesson.reason_for_abcense }}</td>
                    {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

</div>

{% endblock %}

templates/courses/lesson_detail.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}

<style>
    th, td {
	text-align: center;
	vertical-align: middle;
}



</style>

<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>{{ object.name }}</h2>
    <hr/>
    <p>{{ object.description }}</p>
    <p><b>Домашнее задание:</b></p>
    <p>{{ object.homework }}</p>
    <p><b>Дата:</b> {{ object.date|date }}</p>
    <p><b>Тип урока:</b> {{ object.get_type_display }}</p>
    <hr/>
    <p><b>Курс:</b> <a href="{% url 'courses:course_detail' object.course.pk %}">{{ object.course.name }}</a></p>
    <p><b>Учитель:</b> <a href="{% url 'profiles:teachers_detail' object.teacher.pk %}">{{ object.teacher.full_name }}</a></p>
    <p><b>Группа:</b> <a href="{% url 'profiles:groups_detail' object.group.pk %}">{{ object.group.name }}</a></p>

    <hr/>

    <div class="panel panel-info">
        <div class="panel-heading">Результаты урока</div>
        <div class="panel-body">
            <table class="table table-striped">
                <tr>
                    <th>ФИО ученика</th>
                    <th>Оценки</th>
                </tr>
                {% for student_lesson in student_lessons %}
                <tr>
                    <td>{{ student_lesson.student.full_name }}</td>
                    {% if student_lesson.precense %}
                    <td class="bg-success">{{ student_lesson.mark }}</td>
                    {% else %}
                    <td class="bg-danger">{{ student_lesson.reason_for_abcense }}</td>
                    {% endif %}

                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

</div>

{% endblock %}

templates/courses/lesson_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    {% if permissions %}
    <h2>Добавление урока</h2>
    <hr/>
    <form class='text-left' method="post" action="">
        {% csrf_token %}

        {{ form|bootstrap }}
        <input class="btn btn-lg btn-primary" type="submit" value="Сохранить"/>
    </form>

    {% else %}
    <h2 style="color: red">У Вас нет прав на добавление новых уроков</h2>
    {% endif %}
</div>

</div>

{% endblock %}

templates/courses/student_lesson_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-10 col-sm-offset-0 text-left'>
    {% if permissions %}
    <h2>Добавление урока</h2>

    <form class='text-left' method="post" action="">

        {% csrf_token %}

    <div class="col-sm-0 col-sm-offset-0 text-left">
        <table class="table">
            <tr>
                <td >ФИО ученика</td>
                <td>Присутствие</td>
                <td>Оценка</td>
                <td>Причина отсутствия</td>
            </tr>
            {% for student_lesson in student_lessons %}
            <tr>
                <td><label>{{ student_lesson.student.full_name }}</label></td>
                <td><input class="form-control" id="precense-{{ student_lesson.student.pk}}" name="precense-{{ student_lesson.student.pk}}" type="checkbox" checked="true"></div></td>
                <td><select class="form-control" id="mark-{{ student_lesson.student.pk}}" name="mark-{{ student_lesson.student.pk}}">
                    <option>- </option>
                    <option>A</option>
                    <option>B</option>
                    <option>C</option>
                    <option>D</option>
                    <option>E</option>
                    <option>F</option>
                </select></td>
                <td><input class="form-control" id="reason_for_abcense-{{ student_lesson.student.pk}}" name="reason_for_abcense-{{ student_lesson.student.pk}}" type="text" disabled></input></td>
            </tr>
            {% endfor %}

        </table>

        <label>Домашнее задание</label>
        <p><textarea class="form-control" rows="5" cols="100" id="homework" name="homework"></textarea></p>
        <p><input class="btn btn-lg btn-primary" type="submit" value="Сохранить"/></p>

    </form>

    {% else %}
        <h2 style="color: red">У Вас нет прав на добавление новых уроков</h2>
    {% endif %}
</div>

<script>
{% for student_lesson in student_lessons %}
document.getElementById('precense-{{ student_lesson.student.pk}}').onchange = function() {
    document.getElementById('reason_for_abcense-{{ student_lesson.student.pk}}').disabled = this.checked;
    document.getElementById('mark-{{ student_lesson.student.pk}}').disabled = !this.checked;
};
{% endfor %}
</script>

{% endblock %}

templates/courses/student_lessons.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}

<style>


td.red_white {
	background-color: #F78181;
	color: #505050;
}

td.green_red {
	background-color: #58FA58;
	color: #505050;
}
</style>

<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>{{ user_full_name }}</h2>
    {% for lesson in lessons %}
    <div class="panel panel-info">
        <div class="panel-heading">{{ lesson.lesson.name }} - {{ lesson.lesson.date }}</div>
        <div class="panel-body">
            <table class="table table-striped">
                <tr>
                    <th>Курс</th>
                    <td>{{ lesson.lesson.course }}</td>
                </tr>
                <tr>
                    <th>Тип урока</th>
                    <td>{{ lesson.lesson.get_type_display }}</td>
                </tr>
                <tr>
                    <th>Успеваемость</th>
                    {% if lesson.precense %}
                        <td class="bg-success">{{ lesson.mark }}</td>
                    {% else %}
                        <td class="bg-danger">{{ lesson.reason_for_abcense }}</td>
                    {% endif %}
                </tr>
            </table>
        </div>
    </div>
    {% endfor %}


</div>

{% endblock %}

templates/courses/teacher_lessons.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class='col-sm-7 col-sm-offset-0 text-left'>
    <h2>{{ user_full_name }}</h2>
    {% for lesson in lessons %}
    <div class="panel panel-info">
        <div class="panel-heading">{{ lesson.name }} - {{ lesson.date }}</div>
        <div class="panel-body">
            <table class="table table-striped">
                <tr>
                    <th>Курс</th>
                    <td>{{ lesson.course }}</td>
                </tr>
                <tr>
                    <th>Тип урока</th>
                    <td>{{ lesson.type }}</td>
                </tr>
                <tr>
                    <th>Количество студентов</th>
                    <td>{{ lesson.students }}</td>
                </tr>
            </table>
        </div>
    </div>
    {% endfor %}


</div>

{% endblock %}